language: python
cache: pip
dist: trusty

matrix:
  include:
   - env: TOXENV=dj20-wagtail22-py34
     python: 3.4
   - env: TOXENV=dj20-wagtail22-py35
     python: 3.5
   - env: TOXENV=dj20-wagtail22-py36
     python: 3.6
   - env: TOXENV=dj20-wagtail23-py34
     python: 3.4
   - env: TOXENV=dj20-wagtail23-py35
     python: 3.5
   - env: TOXENV=dj20-wagtail23-py36
     python: 3.6
   - env: TOXENV=dj20-wagtail24-py34
     python: 3.4
   - env: TOXENV=dj20-wagtail24-py35
     python: 3.5
   - env: TOXENV=dj20-wagtail24-py36
     python: 3.6
   - env: TOXENV=dj20-wagtail25-py34
     python: 3.4
   - env: TOXENV=dj20-wagtail25-py35
     python: 3.5
   - env: TOXENV=dj20-wagtail25-py36
     python: 3.6

install:
  - pip install tox codecov

script:
  tox
